### ISSUE TITLE
Reproduce line-diff SantaCoder fine-tuned on CommitPackFT (Table 11) results 

### ISSUE THREAD

**Issue by JiyangZhang** [bigcode-project/octopack#26]
Hi,

I am excited about line-diff SantaCoder model and was trying to reproduce the results in Table 11 in the appendix!

I am wondering which dataset did you use for finetuning SantaCoder. Based on the descriptions from the paper, you used the subset (Java, Js, Py) of COMMITPACKFT which after I processing by myself gives me ~129K rows. The name of the dataset is **"bigcode/commits-pjj-2048"** in the finetune.sh script in the repository.

Could you please share the bigcode/commits-pjj-2048 dataset? I would really appreciate it!

Best.

**Comment by Muennighoff** [comment]
Just made `bigcode/commits-pjj-2048` public: https://huggingface.co/datasets/bigcode/commits-pjj-2048
but yeah it should be ~same as Java,Js,Py of CommitPackFT

**Comment by JiyangZhang** [comment]
Thank you very much!

Actually, if I sum the number of examples of Java, Js and Py of CommitPackFT, it gives me ~129K. This number can be computed from the dataset: https://huggingface.co/datasets/bigcode/commitpackft and Appendix C in the paper as well. (The dataset you shared contains ~1.8M examples but CommitPackFT only has 702K examples. 

Maybe something is off here?
